name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "alabama-jackson"
          heroku_email: "harekrishna@gmail.com"
          docker_heroku_process_type: "bot" #OPTIONAL and DEFAULT - "web"
